title: Mike Haxel's Professional Portfolio
logo: "Ralph.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center><b>Data Analyst at F.W. Haxel Company</b></center> 
  <br>
  <b>Masters of Geographic Information Systems (MGIS)</b>
  <br>
  <b>The Pennsylvania State University, 2021</b>
  <br><br>
  <a href="https://www.linkedin.com/in/michael-haxel-2623848a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
