title: Mike Haxel's Professional Portfolio
logo: #"Ralph.JPG" # Photo Logo
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center><b>Data Analyst at F.W. Haxel Company</b></center> 
  <center><b>Masters of Geographic Information Systems (MGIS)</b></center>
  <center><b>Penn State University, 2021</b></center>

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-minimal
show_downloads: false
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
